### ISSUE TITLE
Frontend Linter

### ISSUE THREAD

**Issue by PascalHonegger** [PascalHonegger/ChaosConnect#37]
The frontend currently does not enforce any kind of coding style, but there [existing useful plugins](https://github.com/sveltejs/eslint-plugin-svelte3) are which would allow us to enforce some sort of consistent coding style.

**Comment by arekisanda** [comment]
What about recommended tslint or typescript-eslint rules + prettier checks?
I have done it before and could easily integrate proven configurations. Should I look into it?

**Comment by PascalHonegger** [comment]
A eslint & prettier setup would be nice but isn't a priority give the time horizon if the project. By the way, tslint is deprecated 😁

**Comment by PascalHonegger** [comment]
Closed due to project completion
