### ISSUE TITLE
Release V1.0 with required documentation

### ISSUE THREAD

**Issue by PascalHonegger** [PascalHonegger/ChaosConnect#71]
- [ ] Document project idea
  - [ ] Game rules
- [ ] Document Infrastructure
  - [ ] Docker setup
  - [ ] Reverse-Proxy
  - [ ] Continous Integration & Continous Delivery
  - [ ] Certificate with Certbot for production
  - [ ] Linode hosted server
- [ ] Document Architecture
  - [ ] Which service has which responsibilities
  - [ ] Simple data flow
  - [ ] JSON Storage without database
  - [ ] How configuration is handled
  - [ ] Testability (200+ Unit Tests)
- [ ] Document Design decisions
  - [ ] Why gRPC
  - [ ] Why Micronaut
  - [ ] Why Kotlin
  - [ ] Why Svelte
  - [ ] Why Envoy
  - [ ] Why symmetric JWT
  - [ ] Why real time updates with change events instead of whole state
- [ ] Aggregate documentation into PDF
- [ ] Release Version 1.0 with deliverables attached
- [ ] Send E-Mail for hand in

**Comment by arekisanda** [comment]
We could put everything in README.md, add a table of contents and compile it to PDF (e. g. using pandoc). What do you think?

**Comment by PascalHonegger** [comment]
I agree that we should put everything in the README, I'm not sure how to aggregate to PDF yet. Pandoc is a solution, copy-pasting into PowerPoint also seems reasonable. If you have experience with pandoc a simple Markdown-to-PDF seems like a good idea.
Either way, we should start completing the README and look into the PDF later.

**Comment by arekisanda** [comment]
Current structure:
```
# ChaosConnect 
# Gameplay
# Running for Production
## Prerequisites
## Starting
# Development
# Technical Implementation
## Service Names
## Frontend
## Reverse Proxy
## Backend
## Database
## Communication
```

**Comment by arekisanda** [comment]
The task `Document project idea` seems to be covered by the section `ChaosConnect`.
The sub-task `Game rules` seems to be covered by the sub-section `Gameplay`.
Should we rename the section `ChaosConnect` to `Project Idea`?
Should we rename the section `Gameplay` to `Game Rules`?
Should we convert the section `Gameplay` to a sub-section?

**Comment by PascalHonegger** [comment]
My checkmarks are structured in this way to make sure no point gets forgotten, our documentation should have a logical structure and must not adhere strictly to these bullet points. If you think some points are covered you can check them off. If you think some re-grouping makes sense go ahead.
E.g. the title Gameplay probably makes sense but maybe the content should be seperatet into Rules & Future Plans.

**Comment by arekisanda** [comment]
We could introduce a `CI/CD` section as well. The sections `Running for Production` and `Development` would make for suitable sub-sections.

> E.g. the title Gameplay probably makes sense but maybe the content should be seperatet into Rules & Future Plans.

Where would you draw the line between `Rules` and `Future Plans`?
Here is my assessment:

> # Rules
> - There are two main fractions: Yellow vs Red
> - There's only one big playing field for all players
> - Each player can make a move after a certain timeout
> - Other players cannot place a chip close to another chip for a certain timeout
> - If more people join, the timeouts are altered, and the playing field scales automatically
>   - More people => make playing field wider
>   - More people => make playing field slightly higher
>   - Fewer people => Mark (now superfluous) rows and columns as soon to be deleted, delete after a certain time passed

Width / columns: OK, although I think that the resizing part needs more testing.
Height / rows: Seems to be OK.

> - If a disk you placed is part of a 4 disk long line you get points, and the associated columns are cleared
> 
> # Future Plans
> - You get more points if you're on the losing fraction for balance purposes
> - You can exchange your points for perks and skins
> - To ensure fairness, some bots might be added to balance the teams
